### PR TITLE
Small ui fixes

### LINKED ISSUE #145: fix: make SeatDistribution view scroll horizontally
When testing a PR, it was discovered (or remembered) that the SeatDistribution view is broken for common laptop screen sizes -- there is no horizontal scroll bar and parties are out of view. This should be addressed.

One solution would be to allow full names of parties, and simply ensure that it scrolls properly.

### LINKED ISSUE #166: fix: checkbox for showing all parties does not get enough space
When I change the year to 2001, the label of the checkbox for showing all parties does not get enough space:
image
This happens in the full-size version of the site, does not appear to be an issue for the mobile version.

### LINKED ISSUE #167: fix: scrollbar is visible even when site fits on screen
The scrollbar for the page is visible, even when the content fit within a single screen:
image

### LINKED ISSUE #169: fix: navigation menu does not disappear when tapping outside it on touch devices
The drop-down menu does not close when tapping outside the menu on touch devices.
image

### LINKED ISSUE #189: fix: make SeatRemainders view scroll horizontally

### LINKED ISSUE #190: style: make SingleDistrict info-box parties indicated
The parties should be indicated (bold/underline, something else), and we might want to consider using the full name in the info box rather than the party code (or using abbr to show partyname).

### LINKED ISSUE #191: style: ComputationMenu reset button "nåværende" -> "historisk"
None of the elections we have are "current", they are all historical records.

### LINKED ISSUE #196: feature: add modal on first load that gives a quick introduction to Lavinia
Explain how information buttons/tooltips work, link to wiki, etc.

### LINKED ISSUE #222: style: "Vis alle partier" -> "Inkluder partier uten mandater"
Much more clear indicator of what the button does.

### LINKED ISSUE #224: fix(cypress): Update the Cypress checkbox IDs to match the new switch IDs
In a recent merge the IDs of the checkboxes were changed. This caused a number of Cypress tests to fail. The Cypress tests need to be updated to match the new checkbox names.

### PR DESCRIPTION
**Pull request by Log234**
# Description
Fixes a number of simple UI issues. See the related issues for description of each.

## Issues closed
Closes #145 
Closes #166 
Closes #167 
Closes #169 
Closes #189 
Closes #190 
Closes #191 
Closes #196 
Closes #222 
Closes #224

### CODE REVIEW

File: src/Layout/Presentation/SingleDistrict/InfoBox.tsx [hunk 1]
```diff
@@ -1,13 +1,16 @@
 import * as React from "react";
 import { VulnerableDistrictSeat, VulnerableVotes } from "../../../utilities/district";
+import { Dictionary } from "utilities/dictionary";
```
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:3]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

File: src/Layout/Tutorial/Tutorial.tsx [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+export class Tutorial extends React.Component<TutorialProps, {}> {
+
+    public render() {
+        const showTutorial = this.props.showTutorial ? " is-active" : "" ;
+        const modalClass = "modal" + showTutorial;
+
+        return (
+            <div className={modalClass}>
+            <div className="modal-background" onClick={() => this.props.closeTutorial()}></div>
```
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:15]: Codacy found an issue: [Lambdas are forbidden in JSX attributes due to their rendering performance impact](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-actions.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 ﻿import { ElectionType, Votes, Metrics, Parameters } from "./requested-data-models";
+import { Dictionary } from "utilities/dictionary";
```
Comment (Log234) [inline src/requested-data/requested-data-actions.ts:2]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx [hunk 4]
```diff
@@ -15,6 +15,7 @@ import {
     getVulnerableSeatByVotes,
 } from "../../../utilities/district";
 import { isQuotientAlgorithm } from "../../../computation/logic";
+import { Dictionary } from "utilities/dictionary";
```
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx:18]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/InfoBox.tsx (hunk 1 above)
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:3]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/InfoBox.tsx [hunk 5]
```diff
@@ -16,7 +19,7 @@ export class InfoBox extends React.Component<InfoBoxProps> {
                       " hadde nærmeste kvotient og trengte ",
                       vulnerable.moreVotesToWin,
                       " flere stemmer for å vinne mandatet. ",
-                          vulnerableVotes.partyCode,
+                          <b>{partyMap[vulnerableVotes.partyCode]}</b>,
```
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:22]: Codacy found an issue: [Missing "key" prop for element.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx (hunk 4 above)
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx:18]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+            <div className="modal-card">
+                <header className="modal-card-head">
+                <p className="modal-card-title">Velkommen til Lavinia</p>
+                <button className="delete" aria-label="close" onClick={() => this.props.closeTutorial()}></button>
```
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:19]: Codacy found an issue: [Lambdas are forbidden in JSX attributes due to their rendering performance impact](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/Presentation.tsx [hunk 7]
```diff
@@ -18,6 +18,7 @@ import { LagueDhontResult, PartyResult, DistrictResult, AlgorithmType } from "..
 import { PresentationType, DisproportionalityIndex } from "./presentation-models";
 import { ElectionComparison } from "./ElectionOverview/ElectionComparison";
 import { checkExhaustively } from "../../utilities";
+import { Dictionary } from "utilities/dictionary";
```
Comment (Log234) [inline src/Layout/Presentation/Presentation.tsx:21]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-actions.ts (hunk 3 above)
Comment (Log234) [inline src/requested-data/requested-data-actions.ts:2]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/Presentation.tsx (hunk 7 above)
Comment (Log234) [inline src/Layout/Presentation/Presentation.tsx:21]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-state.ts [hunk 8]
```diff
@@ -1,4 +1,5 @@
 import { ElectionType, Votes, Metrics, Parameters } from "./requested-data-models";
+import { Dictionary } from "utilities/dictionary";
```
Comment (Log234) [inline src/requested-data/requested-data-state.ts:2]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 2 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:15]: Codacy found an issue: [JSX elements with no children must be self-closing](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/ConnectedTutorial.tsx [hunk 9]
```diff
@@ -0,0 +1,17 @@
+import { RootState } from "reducers";
```
Comment (Log234) [inline src/Layout/Tutorial/ConnectedTutorial.tsx:1]: Codacy found an issue: [Module 'reducers' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/ConnectedLayout.tsx [hunk 10]
```diff
@@ -7,35 +7,30 @@ import {
...
     InitializeRequestedParameters,
+    initializeRequestedPartyMap,
 } from "../requested-data";
 import { initializeComputation } from "../computation";
 import { initializeComputationMenu } from "./ComputationMenu";
 import { initializePresentation } from "./PresentationMenu";
 import { stateIsInvalid } from "../store/version";
 import { rawParametersToParametersConverter } from "../requested-data/requested-data-utilities";
 import { RootState } from "../reducers";
+import { Dictionary } from "utilities/dictionary";
```
Comment (Log234) [inline src/Layout/ConnectedLayout.tsx:18]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 6 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:19]: Codacy found an issue: [JSX elements with no children must be self-closing](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-state.ts (hunk 8 above)
Comment (Log234) [inline src/requested-data/requested-data-state.ts:2]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+                        For å lese mer som Lavinia og det norske valgsystemet
+                        kan du ta en titt på wikien vår: 
+                         <a target="_blank"
+                            rel="noopener noreferrer"
+                            href="https://project-lavinia.github.io/#Lavinia"> https://project-lavinia.github.io/#Lavinia
+                            </a>
+                    </p> 
+                </section>
+                <footer className="modal-card-foot">
+                    <button className="button" onClick={() => this.props.closeTutorial()}>Ok</button>
```
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:43]: Codacy found an issue: [Lambdas are forbidden in JSX attributes due to their rendering performance impact](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/ui-reducer.ts [hunk 12]
```diff
@@ -25,14 +28,31 @@ export interface ToggleHamburger {
     hamburgerExpanded: boolean;
 }
 
-export function ui(state: UiState = defaultState, action: ToggleHamburger): UiState {
+export function hideTutorial() {
+    const action: HideTutorial  = {
+        type: UiActionType.HIDE_TUTORIAL
+    }
```
Comment (Log234) [inline src/Layout/ui-reducer.ts:34]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/ConnectedLayout.tsx (hunk 10 above)
Comment (Log234) [inline src/Layout/ConnectedLayout.tsx:18]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 20
           

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

File: src/Layout/ConnectedLayout.tsx (hunk 10 above)
Comment (Log234) [inline src/Layout/ConnectedLayout.tsx:18]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 6 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:19]: Codacy found an issue: [Lambdas are forbidden in JSX attributes due to their rendering performance impact](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx (hunk 4 above)
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx:18]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-state.ts (hunk 8 above)
Comment (Log234) [inline src/requested-data/requested-data-state.ts:2]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 11 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:43]: Codacy found an issue: [Lambdas are forbidden in JSX attributes due to their rendering performance impact](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/ConnectedLayout.tsx (hunk 10 above)
Comment (Log234) [inline src/Layout/ConnectedLayout.tsx:18]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/InfoBox.tsx (hunk 1 above)
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:3]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:3]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 2 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:15]: Codacy found an issue: [JSX elements with no children must be self-closing](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/ui-reducer.ts (hunk 12 above)
Comment (Log234) [inline src/Layout/ui-reducer.ts:34]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-actions.ts (hunk 3 above)
Comment (Log234) [inline src/requested-data/requested-data-actions.ts:2]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 2 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:15]: Codacy found an issue: [Lambdas are forbidden in JSX attributes due to their rendering performance impact](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/Presentation.tsx (hunk 7 above)
Comment (Log234) [inline src/Layout/Presentation/Presentation.tsx:21]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-state.ts (hunk 8 above)
Comment (Log234) [inline src/requested-data/requested-data-state.ts:2]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/InfoBox.tsx (hunk 5 above)
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:22]: Codacy found an issue: [Missing "key" prop for element.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx (hunk 4 above)
Comment (Log234) [inline src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx:18]: Codacy found an issue: [Submodule import paths from this package are disallowed; import from the root instead](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx (hunk 6 above)
Comment (Log234) [inline src/Layout/Tutorial/Tutorial.tsx:19]: Codacy found an issue: [JSX elements with no children must be self-closing](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/ConnectedTutorial.tsx (hunk 9 above)
Comment (Log234) [inline src/Layout/Tutorial/ConnectedTutorial.tsx:1]: Codacy found an issue: [Module 'reducers' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/requested-data/requested-data-actions.ts (hunk 3 above)
Comment (Log234) [inline src/requested-data/requested-data-actions.ts:2]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Presentation/Presentation.tsx (hunk 7 above)
Comment (Log234) [inline src/Layout/Presentation/Presentation.tsx:21]: Codacy found an issue: [Module 'utilities' is not listed as dependency in package.json](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

File: src/Layout/Tutorial/Tutorial.tsx [hunk 13]
```diff
@@ -0,0 +1,49 @@
...
+        return (
+            <div className={modalClass}>
+            <div className="modal-background" onClick={() => this.props.closeTutorial()}></div>
+            <div className="modal-card">
+                <header className="modal-card-head">
+                <p className="modal-card-title">Velkommen til Lavinia</p>
+                <button className="delete" aria-label="close" onClick={() => this.props.closeTutorial()}></button>
+                </header>
+                <section className="modal-card-body">
+                    <b>Program tips</b>
```
Comment (simendag) [inline src/Layout/Tutorial/Tutorial.tsx:22]: Word-dividing error.

File: src/Layout/Tutorial/Tutorial.tsx [hunk 14]
```diff
@@ -0,0 +1,49 @@
...
+                    <p>
+                        I Lavinia vil du se hjelpesymboler 
+                        (<i className="fas fa-info-circle has-text-primary" />) 
+                        ved de forskjellige valgmulighetene.
```
Comment (simendag) [inline src/Layout/Tutorial/Tutorial.tsx:26]: "valgmulighet" -> "innstilling" ?

File: src/Layout/Tutorial/Tutorial.tsx [hunk 15]
```diff
@@ -0,0 +1,49 @@
...
+                        Du kan klikke på symbolene for å få mer informasjon.
+                    </p>
+                    <br />
+                    <b>Wiki</b>
+                    <p>
+                        For å lese mer som Lavinia og det norske valgsystemet
+                        kan du ta en titt på wikien vår: 
+                         <a target="_blank"
+                            rel="noopener noreferrer"
+                            href="https://project-lavinia.github.io/#Lavinia"> https://project-lavinia.github.io/#Lavinia
```
Comment (simendag) [inline src/Layout/Tutorial/Tutorial.tsx:38]: This should be using process.env.WIKI probably (check in the env.default file).

File: src/Layout/Tutorial/Tutorial.tsx (hunk 6 above)
Comment (simendag) [inline src/Layout/Tutorial/Tutorial.tsx:19]: The button is quite small and on the wrong side of the screen for most users. I suggest centering it and making it wider so that it is more accessible and looks more symmetrical.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

File: src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx [hunk 16]
```diff
@@ -6,12 +6,14 @@ import { getMostVulnerableSeatByQuotient } from "../../../utilities/district";
...
 import { isQuotientAlgorithm } from "../../../computation/logic";
 import { VulnerableDistrictSeatText } from "./VulnerableDistrictSeatText";
+import { Dictionary } from "lodash";
 
 export interface DistrictOverviewProps {
     districtResults: DistrictResult[];
     districtWidth: number;
     decimals: number;
     algorithm: AlgorithmType;
+    partyMap: Dictionary<string>;
```
Comment (simendag) [inline src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx:16]: We are using a lodash type for this? Is this what you intended? I think we have a utility somewhere that should be removed if we're migrating.

File: src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx [hunk 17]
```diff
@@ -1,21 +1,26 @@
...
+            const partyMap = this.props.partyMap;
+            const winnerPartyCode = this.props.mostVulnerable.winner.partyCode;
+            const runnerUpPartyCode = this.props.mostVulnerable.runnerUp.partyCode;
             return (
                 <React.Fragment>
                     {" Det mest utsatte sistemandatet (relativt til kvotient) var i "}
                     {this.props.mostVulnerable.district}
                     {" og ble vunnet av "}
-                    {this.props.mostVulnerable.winner.partyCode}
+                    <b>{partyMap[winnerPartyCode]}</b>
```
Comment (simendag) [inline src/Layout/Presentation/DistrictOverview/VulnerableDistrictSeatText.tsx:21]: Isn't it better to use classes to define appearance / visual behaviour like this?

File: src/Layout/Presentation/SingleDistrict/InfoBox.tsx [hunk 18]
```diff
@@ -16,7 +19,7 @@ export class InfoBox extends React.Component<InfoBoxProps> {
                       " hadde nærmeste kvotient og trengte ",
                       vulnerable.moreVotesToWin,
                       " flere stemmer for å vinne mandatet. ",
-                          vulnerableVotes.partyCode,
+                          <b key="vulnerableVotes">{partyMap[vulnerableVotes.partyCode]}</b>,
```
Comment (simendag) [inline src/Layout/Presentation/SingleDistrict/InfoBox.tsx:22]: There are a lot of &lt;b&gt;'s here. It really would be a lot better to have a class, as it might not specify the behaviour we want if it is to be changed at some point in the future (whereas a class would represent the intention/what should be affected).

File: src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx [hunk 19]
```diff
@@ -183,7 +183,7 @@ export class PresentationSettingsMenu extends React.Component<PresentationSettin
         return (
             <div className="columns">
                 <div className="columns">
-                    <div className="column">
+                    <div className="column" style={{minWidth: "10.5rem"}}>
```
Comment (simendag) [inline src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx:186]: This cuts off the the top sliver of the upper-most checkboxes in some cases. It's also not recommended to use "style" to define things like this. It should be part of a class if it's going to be included (but it is broken, so needs fixing).

File: src/Layout/Tutorial/Tutorial.tsx [hunk 20]
```diff
@@ -0,0 +1,49 @@
...
+                            For å lese mer som Lavinia og det norske valgsystemet
+                            kan du ta en titt på wikien vår: 
+                            <a target="_blank"
+                                rel="noopener noreferrer"
+                                href={process.env.WIKI + "#Lavinia"}> {process.env.WIKI + "#Lavinia"}
+                                </a>
+                        </p> 
+                    </section>
+                    <footer className="modal-card-foot has-text-centered" style={{justifyContent: "center"}}>
+                        <button className="button is-medium" onClick={this.props.closeTutorial}>Ok</button>
```
Comment (simendag) [inline src/Layout/Tutorial/Tutorial.tsx:43]: I would replace the "Ok" with "OK" or 🆗

File: src/blue-theme.scss [hunk 21]
```diff
@@ -13,6 +13,10 @@ $primary: $democracy-blue;
 @import "../node_modules/bulma-switch/dist/css/bulma-switch.sass";
 
 
+html {
+    overflow-y: auto;
```
Comment (simendag) [inline src/blue-theme.scss:17]: How sure are we that this won't have side-effects in the appearance of various segments? Did we test it properly after this was added? A "html" element has to be overwritten anywhere it goes. It might be better to define this behaviour in a class and apply it.

File: src/requested-data/requested-data-actions.ts [hunk 22]
```diff
@@ -8,6 +9,7 @@ export enum RequestedDataActionType {
     INTIIALIZE_REQUESTED_VOTES = "INITIALIZE_REQUESTED_VOTES",
     INITIALIZE_REQUESTED_METRICS = "INITIALIZE_REQUESTED_METRICS",
     INIITALIZE_REQUESTED_PARAMETERS = "INITIALIZE_REQUESTED_PARAMETERS",
+    INIITALIZE_REQUESTED_PARTY_MAP = "INTITIALIZE_REQUESTED_PARTY_MAP",
```
Comment (simendag) [inline src/requested-data/requested-data-actions.ts:12]: Typos galore.

File: src/requested-data/requested-data-reducer.ts [hunk 23]
```diff
@@ -47,6 +48,12 @@ export function requestedData(
...
                 dataLoaded: checkStateLoaded(state, action),
             };
+        case RequestedDataActionType.INIITALIZE_REQUESTED_PARTY_MAP:
+            return {
+                ...state,
+                partyMap: action.partyMap,
+                dataLoaded: checkStateLoaded(state, action),
+            };
         default:
             return state;
```
Comment (simendag) [inline src/requested-data/requested-data-reducer.ts:58]: This is missing the fancy case-checker.

File: src/requested-data/requested-data-state.ts [hunk 24]
```diff
@@ -7,6 +8,7 @@ export interface RequestedDataState {
     votes: Votes[];
     metrics: Metrics[];
     parameters: Parameters[];
+    partyMap: Dictionary<string>
```
Comment (simendag) [inline src/requested-data/requested-data-state.ts:11]: This requires at the very least a minor bump in versioning if I recall correctly.

Comment (Log234) [reply src/requested-data/requested-data-state.ts:11]: Yup.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by simendag** [comment]
For some reason we now have two links to GitHub?

I fixed this in 2.8.0, as mentioned previously.

File: src/requested-data/requested-data-reducer.ts [hunk 25]
```diff
@@ -37,21 +38,28 @@ export function requestedData(
...
             };
-        case RequestedDataActionType.INIITALIZE_REQUESTED_PARTY_MAP:
+        case RequestedDataActionType.INITIALIZE_REQUESTED_PARTY_MAP:
             return {
                 ...state,
                 partyMap: action.partyMap,
                 dataLoaded: checkStateLoaded(state, action),
                 enableAutoSave: checkStateLoaded(state, action),
             };
+        case RequestedDataActionType.INITIALIZE_REQUESTED_PARTY_MAP:
```
Comment (Log234) [inline src/requested-data/requested-data-reducer.ts:55]: Codacy found an issue: [Duplicate switch case: 'RequestedDataActionType.INITIALIZE_REQUESTED_PARTY_MAP'.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

File: src/requested-data/requested-data-reducer.ts (hunk 25 above)
Comment (Log234) [inline src/requested-data/requested-data-reducer.ts:55]: Codacy found an issue: [Duplicate case label.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793)

**Comment by Log234** [comment]
> 
> 
> For some reason we now have two links to GitHub?
> 
> I fixed this in 2.8.0, as mentioned previously.

Cleaned it up.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by simendag** [comment]
I'll try to get this running and see if there is anything left to fix sometime tomorrow; weekend was a lot more hectic than I had expected.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/ui-reducer.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5947793&bid=19497413)
