### PR TITLE
fix: disable clearing of local storage

### LINKED ISSUE #209: fix: handle errors when requesting data from the API
Currently we are not handling any errors that may occur when requesting data from the API.
We should add handling for if the client sends a request to an endpoint too frequently:
Wait until the timeout expires and try again, if it does not succeed within 5 attempts, then crash gracefully.

### LINKED ISSUE #210: fix: keep Cypress from reaching the request limit on the API
Currently Cypress is not caching data and rapidly sends requests to the API. That will not work with the new request limit, and so we need to find a way to handle it.

Two ideas:
 * Re-enable the cache, so Cypress doesn't have to request data from the API every refresh
 * Ensure Cypress sends requests slower than the API limit by pausing the program before the page is refreshed

### LINKED ISSUE #217: refactor: Replace Axios with fetch
We should use Fetch instead of Axios to request data from the API.

### PR DESCRIPTION
**Pull request by Log234**
# Description
Disables clearing of local storage in Cypress.

Reduces Cypress data download 128MB -> 46MB
Reduces Cypress run time 140min -> 57 min

## Issues closed
Closes #209 
Closes #210 
Closes #217

### CODE REVIEW

File: src/utilities/api-requests.ts [hunk 1]
```diff
@@ -10,13 +11,22 @@ import axios from "axios";
...
+        await axios
+            .get(uri)
+            .then((res: AxiosResponse) => {
+                data = res.data as T;
+            })
+            .catch((reason: AxiosError) => {
+                console.error(`Request to ${uri} failed with\n${reason}`);
+            });
+
+        if (data == defaultValue) {
```
Comment (Log234) [inline src/utilities/api-requests.ts:26]: Codacy found an issue: [== should be ===](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)

File: src/utilities/api-requests.ts [hunk 2]
```diff
@@ -10,13 +11,22 @@ import axios from "axios";
...
-        .get(uri)
-        .then((res) => {
-            data = res.data as T;
-        })
-        .catch((error) => {
-            console.error(`Request to ${uri} failed with\n${error}`);
-        });
+    let attempt = 0;
+
+    while (data == defaultValue && attempt < 5) {
```
Comment (Log234) [inline src/utilities/api-requests.ts:16]: Codacy found an issue: [== should be ===](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 3]
```diff
@@ -10,13 +11,22 @@ import axios from "axios";
...
+        await axios
+            .get(uri)
+            .then((res: AxiosResponse) => {
+                data = res.data as T;
+            })
+            .catch((reason: AxiosError) => {
+                console.error(`Request to ${uri} failed with\n${reason}`);
```
Comment (Log234) [inline src/utilities/api-requests.ts:23]: Codacy found an issue: [Unexpected console statement.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 4]
```diff
@@ -10,13 +11,22 @@ import axios from "axios";
...
+            });
+
+        if (data == defaultValue) {
+            console.log("Requesting: " + uri + " attempt: " + ++attempt);
```
Comment (Log234) [inline src/utilities/api-requests.ts:27]: Codacy found an issue: [Unexpected console statement.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 5]
```diff
@@ -10,13 +11,22 @@ import axios from "axios";
...
-        })
-        .catch((error) => {
-            console.error(`Request to ${uri} failed with\n${error}`);
-        });
+    let attempt = 0;
+
+    while (data == defaultValue && attempt < 5) {
+        await axios
+            .get(uri)
+            .then((res: AxiosResponse) => {
```
Comment (Log234) [inline src/utilities/api-requests.ts:19]: Codacy found an issue: [Function declared in a loop contains unsafe references to variable(s) 'data'.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 6]
```diff
@@ -10,13 +11,22 @@ import axios from "axios";
...
+                data = res.data as T;
+            })
+            .catch((reason: AxiosError) => {
+                console.error(`Request to ${uri} failed with\n${reason}`);
+            });
+
+        if (data == defaultValue) {
+            console.log("Requesting: " + uri + " attempt: " + ++attempt);
+            await new Promise(resolve => setTimeout(resolve, 30000));
```
Comment (Log234) [inline src/utilities/api-requests.ts:28]: Codacy found an issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 7]
```diff
@@ -1,4 +1,5 @@
 import axios from "axios";
+import { AxiosResponse, AxiosError } from "axios";
```
Comment (Log234) [inline src/utilities/api-requests.ts:2]: Codacy found an issue: [Multiple imports from 'axios' can be combined into one.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts (hunk 1 above)
Comment (Log234) [inline src/utilities/api-requests.ts:26]: Codacy found an issue: [Expected '===' and instead saw '=='.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts (hunk 2 above)
Comment (Log234) [inline src/utilities/api-requests.ts:16]: Codacy found an issue: [Expected '===' and instead saw '=='.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)

File: src/utilities/api-requests.ts [hunk 8]
```diff
@@ -10,13 +10,26 @@ import axios from "axios";
...
     let data = defaultValue;
-    await axios
-        .get(uri)
-        .then((res) => {
-            data = res.data as T;
-        })
-        .catch((error) => {
-            console.error(`Request to ${uri} failed with\n${error}`);
-        });
+    let attempt = 0;
```
Comment (Log234) [inline src/utilities/api-requests.ts:13]: Codacy found an issue: [Identifier 'attempt' is never reassigned; use 'const' instead of 'let'.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 9]
```diff
@@ -10,13 +10,26 @@ import axios from "axios";
...
+
+    while (data === defaultValue && attempt < 5) {
+        let response = await axios
+            .get<T>(uri)
+            .catch((reason: AxiosError) => handleError(uri, reason));
```
Comment (Log234) [inline src/utilities/api-requests.ts:18]: Codacy found an issue: ['handleError' was used before it was defined.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 10]
```diff
@@ -10,13 +10,26 @@ import axios from "axios";
...
-        .then((res) => {
-            data = res.data as T;
-        })
-        .catch((error) => {
-            console.error(`Request to ${uri} failed with\n${error}`);
-        });
+    let attempt = 0;
+
+    while (data === defaultValue && attempt < 5) {
+        let response = await axios
```
Comment (Log234) [inline src/utilities/api-requests.ts:16]: Codacy found an issue: [Identifier 'response' is never reassigned; use 'const' instead of 'let'.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 11]
```diff
@@ -10,13 +10,26 @@ import axios from "axios";
...
+            .get<T>(uri)
+            .catch((reason: AxiosError) => handleError(uri, reason));
+
+        if (response) {
+            if (response.status === 200) {
+                data = response.data;
+            } else if (response.status === 429) {
+                await new Promise(resolve => setTimeout(resolve, 30000));
```
Comment (Log234) [inline src/utilities/api-requests.ts:24]: Codacy found an issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 12]
```diff
@@ -10,13 +10,26 @@ import axios from "axios";
...
+            } else {
+                await new Promise(resolve => setTimeout(resolve, 5000));
```
Comment (Log234) [inline src/utilities/api-requests.ts:26]: Codacy found an issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 13]
```diff
@@ -10,13 +10,26 @@ import axios from "axios";
...
+            }
+        }
+    }
     return data;
 }
+
+function handleError(uri: string, reason: AxiosError) {
+    console.error(`Request to ${uri} failed with\n${reason}`);
```
Comment (Log234) [inline src/utilities/api-requests.ts:34]: Codacy found an issue: [Unexpected console statement.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: cypress/integration/computation_menu.spec.ts [hunk 14]
```diff
@@ -36,7 +36,6 @@ function waitForLoad(iteration: number = 0) {
 
 describe("ComputationMenu", () => {
     beforeEach(() => {
-        cy.clearLocalStorage();
         cy.viewport(1080, 720);
```
Comment (simendag) [inline cypress/integration/computation_menu.spec.ts:39]: Why are we using 1080 x 720 viewports?

File: src/utilities/api-requests.ts [hunk 15]
```diff
@@ -1,4 +1,9 @@
-import axios from "axios";
+import axios, { AxiosError } from "axios";
+
+
+function handleError(uri: string, reason: AxiosError) {
+    console.error(`Request to ${uri} failed with\n${reason}`);
+}
```
Comment (simendag) [inline src/utilities/api-requests.ts:6]: We might consider replacing Axios with fetch, since fetch is quite ubiquitous in browsers these days.

File: src/utilities/api-requests.ts [hunk 16]
```diff
@@ -10,13 +15,23 @@ import axios from "axios";
...
     let data = defaultValue;
-    await axios
-        .get(uri)
-        .then((res) => {
-            data = res.data as T;
-        })
-        .catch((error) => {
-            console.error(`Request to ${uri} failed with\n${error}`);
-        });
+    let attempt = 0;
```
Comment (simendag) [inline src/utilities/api-requests.ts:18]: Given that we are using Axios, why not use [axios-retry](https://github.com/softonic/axios-retry) to handle this kind of logic instead?

Comment (simendag) [reply src/utilities/api-requests.ts:18]: If we do not use axios-retry, how about storing the error-ed results in an array and doing a .length on it? And possibly logging the error results to console at the end?

We might even use this information later for a toast explaining to the user that there is some connection issue/rate limiting issue.

File: src/utilities/api-requests.ts [hunk 17]
```diff
@@ -10,13 +15,23 @@ import axios from "axios";
...
+    while (data === defaultValue && attempt < 5) {
+        const response = await axios
+            .get<T>(uri)
+            .catch((reason: AxiosError) => handleError(uri, reason));
+
+        if (response) {
+            if (response.status === 200) {
+                data = response.data;
+            } else if (response.status === 429) {
+                await new Promise((resolve) => setTimeout(resolve, 30000));
```
Comment (simendag) [inline src/utilities/api-requests.ts:29]: Magic number (though it is reasonably clear what it is, it wouldn't hurt to have some variable named with what 30000 represents).

File: src/utilities/api-requests.ts [hunk 18]
```diff
@@ -10,13 +15,23 @@ import axios from "axios";
...
+            } else {
+                await new Promise((resolve) => setTimeout(resolve, 5000));
```
Comment (simendag) [inline src/utilities/api-requests.ts:31]: Magic number, see 30000 comment.

File: src/utilities/api-requests.ts [hunk 19]
```diff
@@ -10,13 +15,23 @@ import axios from "axios";
...
-        });
+    let attempt = 0;
+
+    while (data === defaultValue && attempt < 5) {
+        const response = await axios
+            .get<T>(uri)
+            .catch((reason: AxiosError) => handleError(uri, reason));
+
+        if (response) {
+            if (response.status === 200) {
```
Comment (simendag) [inline src/utilities/api-requests.ts:26]: Is 200 OK actually the only Success HTTP-code we can get here? I suppose it is defined in the API. Not very resistant to change, however, if the API is updated to include more success codes.

File: cypress/integration/computation_menu.spec.ts [hunk 20]
```diff
@@ -36,7 +36,6 @@ function waitForLoad(iteration: number = 0) {
 
 describe("ComputationMenu", () => {
     beforeEach(() => {
-        cy.clearLocalStorage();
```
Comment (simendag) [inline cypress/integration/computation_menu.spec.ts:39]: Should we perhaps clear once per test file?

File: cypress/integration/computation_menu.spec.ts (hunk 14 above)
Comment (Log234) [reply cypress/integration/computation_menu.spec.ts:39]: Because the default size is so small the page turns to the mobile format.

File: src/utilities/api-requests.ts (hunk 16 above)
Comment (Log234) [reply src/utilities/api-requests.ts:18]: I think it is nice to be able to handle the different codes manually. It turns out the 429 error returns the time the lock is lifted in the header. So we can parse the header and wait the exact time for the API to unlock. We can also handle other error codes so they do not wait as long before retrying.

File: src/utilities/api-requests.ts (hunk 15 above)
Comment (Log234) [reply src/utilities/api-requests.ts:6]: If you think this is valuable, we can do so. What is the advantage of rewriting the code with fetch? Is Axios not well supported?

File: cypress/integration/computation_menu.spec.ts (hunk 14 above)
Comment (simendag) [reply cypress/integration/computation_menu.spec.ts:39]: Hm, could it be a thought to test both sizes?

File: src/utilities/api-requests.ts (hunk 15 above)
Comment (simendag) [reply src/utilities/api-requests.ts:6]: Bandwidth reduction, fewer dependencies with likely vulnerabilities / requiring maintenance (since fetch is a browser API, it updates as you update your browser). We chose Axios at a time when fetch wasn't ready for production use.

File: src/utilities/api-requests.ts (hunk 16 above)
Comment (simendag) [reply src/utilities/api-requests.ts:18]: Neat!

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)

File: cypress/integration/computation_menu.spec.ts (hunk 20 above)
Comment (Log234) [reply cypress/integration/computation_menu.spec.ts:39]: Cypress automatically clears local storage between each test. The command is superfluous unless you need to clear storage in the middle of a test.

Comment (simendag) [reply cypress/integration/computation_menu.spec.ts:39]: Each test category? Or each test, as in 860 times?

**Comment by Log234** [comment]
Just checked Cypress progress. At the current rate, we may be looking at a several hour slow-down due to the rate limiting of the API.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- cypress/support/index.ts  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)

File: cypress/integration/computation_menu.spec.ts (hunk 20 above)
Comment (Log234) [reply cypress/integration/computation_menu.spec.ts:39]: Each test. I have pushed a commit that implements caching and restoring of local storage, to reduce the number of API calls to every 30 seconds, but without slowing down the testing.

File: src/utilities/api-requests.ts (hunk 19 above)
Comment (Log234) [reply src/utilities/api-requests.ts]: Fixed. It now accepts and HTTP codes in the range [200, 300).

File: src/utilities/api-requests.ts (hunk 18 above)
Comment (Log234) [reply src/utilities/api-requests.ts]: Resolved.

File: src/utilities/api-requests.ts (hunk 17 above)
Comment (Log234) [reply src/utilities/api-requests.ts]: Resolved.

File: src/utilities/api-requests.ts (hunk 15 above)
Comment (Log234) [reply src/utilities/api-requests.ts]: Fixed.

File: cypress/integration/computation_menu.spec.ts (hunk 14 above)
Comment (Log234) [reply cypress/integration/computation_menu.spec.ts:44]: I can make an issue.

File: cypress/support/index.d.ts [hunk 21]
```diff
@@ -0,0 +1,5 @@
+declare namespace Cypress {
```
Comment (Log234) [inline cypress/support/index.d.ts:1]: Codacy found an issue: ['namespace' and 'module' are disallowed](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 4
           

Complexity increasing per file
==============================
- cypress/support/index.ts  3
- src/utilities/api-requests.ts  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)

File: cypress/support/index.ts [hunk 22]
```diff
@@ -0,0 +1,7 @@
+Cypress.Commands.add("copyStorage", (fromStorage: { [name: string]: any }, toStorage: { [name: string]: any }) => {
```
Comment (Log234) [inline cypress/support/index.ts:1]: Codacy found an issue: ['Cypress' is not defined.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 23]
```diff
@@ -1,4 +1,58 @@
...
+/**
+ * Delay that is multiplied by attempt number.
+ * Rationale: 1*4 + 2*4 + 3*4 + 4*4 + 5*4 = 60
+ * which is equal to the timeout duration
+ */
+const iterativeDelay = 4000;
+const maxNumberOfAttempts = 5;
+
+function handleError(uri: string, reason: any) {
+    console.error(`Request to ${uri} failed with\n${reason}`);
```
Comment (Log234) [inline src/utilities/api-requests.ts:10]: Codacy found an issue: [Unexpected console statement.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

File: src/utilities/api-requests.ts [hunk 24]
```diff
@@ -9,14 +63,26 @@ import axios from "axios";
...
-    await axios
-        .get(uri)
-        .then((res) => {
-            data = res.data as T;
-        })
-        .catch((error) => {
-            console.error(`Request to ${uri} failed with\n${error}`);
-        });
-    return data;
+    return attemptRequest(uri, defaultValue, 1);
```
Comment (Log234) [inline src/utilities/api-requests.ts:66]: Codacy found an issue: ['attemptRequest' was used before it was defined.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/utilities/api-requests.ts  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=5953345&bid=19512307)
