### PR TITLE
Fix issues

### LINKED ISSUE #106: feat: "Detaljert sammenlikning" -> "Mandatendringer"
This should probably also involve fixing the naming scheme in the code to avoid confusion. The issue may block anything involving the component using this.

### PR DESCRIPTION
**Pull request by oysor**
# Description
Fixed the "good first issue" issues.

## Issues closed
#106 
#107 
#108

### CODE REVIEW

File: src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx [hunk 1]
```diff
@@ -95,8 +95,8 @@ export class ElectionOverview extends React.Component<ElectionOverviewProps, {}>
         }
         const allTrueFalseOptions = [
             { value: "all", title: "Alle" },
-            { value: "true", title: "Ja" },
-            { value: "false", title: "Nei" },
+            { value: "true", title: "Ja >" },
```
Comment (simendag) [inline src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx]:
```suggestion
            { value: "true", title: "> 0" },
```

File: src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx [hunk 2]
```diff
@@ -95,8 +95,8 @@ export class ElectionOverview extends React.Component<ElectionOverviewProps, {}>
...
+            { value: "false", title: "Nei =" },
```
Comment (simendag) [inline src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx]:
```suggestion
            { value: "false", title: "= 0" },
```
