### PR TITLE
fix: keep tooltip from clipping

### LINKED ISSUE #256: Tooltip info partly hidden
The tooltip infobox for 'Disproporsjonalitetsindeks' is not always visible. 

overflow

### PR DESCRIPTION
**Pull request by Log234**
# Description
Keeps the disproportionality index tooltip from clipping the top padding.

## Issues closed
Closes #256

### CODE REVIEW

File: src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx [hunk 1]
```diff
@@ -226,7 +227,7 @@ export class PresentationSettingsMenu extends React.Component<PresentationSettin
                                 changeDisproportionalityIndex={this.props.changeDisproportionalityIndex}
                                 disproportionalityIndex={this.props.disproportionalityIndex}
                                 tooltip={
-                                    <TooltipInfo
+                                    <TooltipInfoBottom
                                         text={"Her kan du velge mellom Loosemore-Hanbys (L-H) og Gallaghers (LSq)."}
```
Comment (simendag) [inline src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx:231]: The ordering of these might benefit from being swapped as Gallagher's index is now the default.

**Review by simendag — CHANGES_REQUESTED** [review]
See comments.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523&bid=19945347)

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 2]
```diff
@@ -1,14 +1,50 @@
...
+    switch (direction) {
+        case undefined:
+        case TooltipDirection.TOP:
+            return base
+        case TooltipDirection.BOTTOM:
+            return base + " has-tooltip-bottom"
+        case TooltipDirection.LEFT:
+            return base + " has-tooltip-left"
+        case TooltipDirection.RIGHT:
+            return base + " has-tooltip-right"
```
Comment (Log234) [inline src/common/TooltipInfo/TooltipInfo.tsx:30]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523)

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 3]
```diff
@@ -1,14 +1,50 @@
...
+        default:
+            checkExhaustively(direction)
+            toast({
+                dismissible: true,
+                duration: 5000,
+                message: `En feil oppstod: TooltipInfo getClassName switch nådde umulig valg: ${direction}`,
+                position: "top-left",
+                type: "is-danger"
+            })
```
Comment (Log234) [inline src/common/TooltipInfo/TooltipInfo.tsx:39]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523)

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 4]
```diff
@@ -1,14 +1,50 @@
...
+    const base = "icon has-tooltip-multiline has-tooltip-arrow";
+
+    switch (direction) {
+        case undefined:
+        case TooltipDirection.TOP:
+            return base
+        case TooltipDirection.BOTTOM:
+            return base + " has-tooltip-bottom"
+        case TooltipDirection.LEFT:
+            return base + " has-tooltip-left"
```
Comment (Log234) [inline src/common/TooltipInfo/TooltipInfo.tsx:28]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523)

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 5]
```diff
@@ -1,14 +1,50 @@
...
+        case TooltipDirection.RIGHT:
+            return base + " has-tooltip-right"
+        default:
+            checkExhaustively(direction)
```
Comment (Log234) [inline src/common/TooltipInfo/TooltipInfo.tsx:32]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523)

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 6]
```diff
@@ -1,14 +1,50 @@
...
+
+function getClassName(direction: TooltipDirection | undefined): string {
+    const base = "icon has-tooltip-multiline has-tooltip-arrow";
+
+    switch (direction) {
+        case undefined:
+        case TooltipDirection.TOP:
+            return base
+        case TooltipDirection.BOTTOM:
+            return base + " has-tooltip-bottom"
```
Comment (Log234) [inline src/common/TooltipInfo/TooltipInfo.tsx:26]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523)

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 7]
```diff
@@ -1,14 +1,50 @@
...
+    direction?: TooltipDirection;
+}
+
+function getClassName(direction: TooltipDirection | undefined): string {
+    const base = "icon has-tooltip-multiline has-tooltip-arrow";
+
+    switch (direction) {
+        case undefined:
+        case TooltipDirection.TOP:
+            return base
```
Comment (Log234) [inline src/common/TooltipInfo/TooltipInfo.tsx:24]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6091523)

File: src/Layout/ComputationMenu/ComputationMenu.tsx [hunk 8]
```diff
@@ -334,9 +334,10 @@ export class ComputationMenu extends React.Component<ComputationMenuProps, {}> {
                         onYearChange={this.onYearChange}
                         year={this.props.settingsPayload.year}
                         tooltip={
-                            <TooltipInfoRight
+                            <TooltipInfo
                                 text={"Her kan du velge året stortingsvalget ble holdt."}
                                 url={WIKIURL + "#Valgt%20%C3%A5r"}
```
Comment (simendag) [inline src/Layout/ComputationMenu/ComputationMenu.tsx:339]: This should probably have been encoded using a function rather than be done manually, but doesn't *need* fixing.

File: src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx [hunk 9]
```diff
@@ -32,9 +32,10 @@ export class PresentationSelection extends React.Component<PresentationSelection
         return (
             <div className="field">
                 <label className="label">
-                    <TooltipInfoRight
+                    <TooltipInfo
                         text={"Trykk på dette ikonet for å lese om oversikten."}
                         url={WIKIURL?.concat("#Visning")}
```
Comment (simendag) [inline src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx:37]: Inconsistent way of handling "url" property. Why isn't it done in the same way in ComputationMenu? Needs addressing.

File: src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx [hunk 10]
```diff
@@ -227,8 +227,9 @@ export class PresentationSettingsMenu extends React.Component<PresentationSettin
                                 disproportionalityIndex={this.props.disproportionalityIndex}
                                 tooltip={
                                     <TooltipInfo
-                                        text={"Her kan du velge mellom Loosemore-Hanbys (L-H) og Gallaghers (LSq)."}
+                                        text={"Her kan du velge mellom Gallaghers (LSq) og Loosemore-Hanbys (L-H)."}
                                         url={"https://project-lavinia.github.io/#Disproporsjonalitetsindeks"}
```
Comment (simendag) [inline src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx:231]: Hard-coded link to the wiki. Needs fixing.

File: src/common/TooltipInfo/TooltipInfo.tsx [hunk 11]
```diff
@@ -1,14 +1,50 @@
...
     text: string;
     url?: string;
+    direction?: TooltipDirection;
+}
+
+function getClassName(direction: TooltipDirection | undefined): string {
+    const base = "icon has-tooltip-multiline has-tooltip-arrow";
+
+    switch (direction) {
+        case undefined:
```
Comment (simendag) [inline src/common/TooltipInfo/TooltipInfo.tsx:22]: This is a strange "fall through". Isn't this handled by "default"?

**Review by simendag — CHANGES_REQUESTED** [review]
Almost there, needs a few small changes. It also doesn't quite solve the problem we set out to solve:
image

File: src/common/TooltipInfo/TooltipInfo.tsx (hunk 11 above)
Comment (Log234) [reply src/common/TooltipInfo/TooltipInfo.tsx:22]: It could be handled by default, but I chose to rather handle it specifically and use checkExhaustively in case we modify the enum in the future and forget updating the switch.

Comment (simendag) [reply src/common/TooltipInfo/TooltipInfo.tsx:22]: Can you address why the undefined part is here at all? I really don't like this behaviour in code. Though to be fair I am increasingly against switches and if-else statements, too, due to their impact on the open closed principle.

**Comment by simendag** [comment]
> > Almost there, needs a few small changes. It also doesn't quite solve the problem we set out to solve:
> > image
> 
> After some more testing, it appears that the tooltip will always clip one side of the screen, either on mobile screens or small laptop/desktop screens.

It is at least an improvement as it is now. One can scroll right a little to see it.

File: src/common/TooltipInfo/TooltipInfo.tsx (hunk 11 above)
Comment (Log234) [reply src/common/TooltipInfo/TooltipInfo.tsx:22]: Undefined is there because direction is an optional property. When the user does not specify any direction, the default direction should be TOP, thus both undefined and TOP have the same code.

Undefined cannot be caught in the default case, as undefined does not match the never in checkExhaustively.

Comment (simendag) [reply src/common/TooltipInfo/TooltipInfo.tsx:22]: if (!direction) return (default enum here) prior to the switch would handle that much better and more explicitly.

Comment (Log234) [reply src/common/TooltipInfo/TooltipInfo.tsx:22]: Could alternatively do something like `const finalDirection = direction || TooltipDirection.TOP`.

**Review by simendag — APPROVED** [review]
