### PR TITLE
fix: Filter parties by national seats

### LINKED ISSUE #266: bug: Disabling show parties without seats filters parties that received seats from the districts they did not receive a seat
Parties that received at least one seat should not be filtered in districts where they did not receive a seat, at least not for the single party view.

### PR DESCRIPTION
**Pull request by Log234**
# Description
Changes Single Party view to filter parties by their national seats, rather than their local ones.

## Issues closed
Closes #266

### CODE REVIEW

File: src/Layout/Presentation/presentation-utilities.ts [hunk 1]
```diff
@@ -1,15 +1,35 @@
...
+function filterPartiesWithoutSeats(partyResults: PartyResult[], nationalResults?: PartyResult[]) {
+    let filteredResults = [...partyResults];
+
+    if (nationalResults) {
+        filteredResults = filteredResults.filter((party) => {
+            const nationalParty = nationalResults.find((nationalParty) => nationalParty.partyCode === party.partyCode);
+            if (!nationalParty) {
+                return false;
+            } else {
+                return nationalParty.totalSeats > 0
```
Comment (Log234) [inline src/Layout/Presentation/presentation-utilities.ts:13]: Codacy found an issue: [Missing semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6141760)

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6141760&bid=20078388)

File: src/Layout/Presentation/Presentation.tsx [hunk 2]
```diff
@@ -55,8 +55,8 @@ export class Presentation extends React.Component<PresentationProps, {}> {
     getSeatDistributionData(): DistrictResult[] {
         return getSeatDistributionData(
             this.props.results.districtResults,
+            this.props.showPartiesWithoutSeats,
             this.props.results.partyResults,
-            this.props.showPartiesWithoutSeats
```
Comment (simendag) [inline src/Layout/Presentation/Presentation.tsx:59]: This is a good example of why one should try to avoid functions with more than two inputs. 😁

I would have to look up the documentation for this function to know what the different things meant and what the ordering was (and why this fixed it).

File: src/Layout/Presentation/presentation-utilities.ts [hunk 3]
```diff
@@ -1,15 +1,35 @@
...
+            const nationalParty = nationalResults.find((nationalParty) => nationalParty.partyCode === party.partyCode);
+            if (!nationalParty) {
+                return false;
+            } else {
+                return nationalParty.totalSeats > 0;
+            }
+        });
+    } else {
+        filteredResults = filteredResults.filter((party) => party.totalSeats > 0);
+    }
```
Comment (simendag) [inline src/Layout/Presentation/presentation-utilities.ts:18]: Why do we use "else"-s here? Wouldn't it be better to specifically state what we're checking for?

File: src/Layout/Presentation/presentation-utilities.ts [hunk 4]
```diff
@@ -1,15 +1,35 @@
...
     showPartiesWithoutSeats: boolean,
-    numberOfDecimals: number
+    numberOfDecimals: number,
+    nationalResults?: PartyResult[],
 ): PartyResult[] {
     let filteredResults = [...partyResults];
 
     if (!showPartiesWithoutSeats) {
-        filteredResults = filteredResults.filter((party) => party.totalSeats > 0);
+        filteredResults = filterPartiesWithoutSeats(filteredResults);
```
Comment (simendag) [inline src/Layout/Presentation/presentation-utilities.ts:32]: Why are we modifying this variable rather than just making a new one so we know exactly what it is in each state?

**Review by simendag — APPROVED** [review]
It looks fine; but I haven't run it. I assume it's been properly tested, and that any strangeness might be picked up by Cypress

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Layout/Presentation/presentation-utilities.ts  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6141760&bid=20078388)

File: src/Layout/Presentation/presentation-utilities.ts (hunk 4 above)
Comment (Log234) [reply src/Layout/Presentation/presentation-utilities.ts]: Because if we stored the result into a second variable, we would essentially have to duplicate the majority of the rest of the function body in a second if statement, which uses one variable or the other depending on whether !showPartiesWithoutSeats is true.

**Comment by Log234** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/Layout/Presentation/presentation-utilities.ts  3
         

Complexity decreasing per file
==============================
+ src/Layout/Presentation/Presentation.tsx  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6141760&bid=20078388)
