### PR TITLE
Fix/remove unusual behaviour

### LINKED ISSUE #101: fix: handle special case of a single district getting less than 2 seats
PWac7jyQNq

### LINKED ISSUE #110: fix(ui):  make "Originalt" go away or have a value for RemainderQuotients Decimals
image

This is no doubt related to SmartNumericInput being changed in the last version.

### PR DESCRIPTION
**Pull request by Log234**
# Description
Fixed bugs causing the app to crash due to invalid party data being passed.

closes #101 
closes #110

### CODE REVIEW

File: src/computation/logic/algorithm-utilities.ts [hunk 1]
```diff
@@ -84,23 +88,16 @@ export function distributeSeats(
...
             }
         }
-        seatsWon[currentWinner.partyCode] += 1;
-        currentSeatsWon[currentWinner.partyCode] += 1;
 
-        const updatedDenominator = getDenominator(algorithm, seatsWon[currentWinner.partyCode], firstDivisor);
-        const updatedQuotient = currentWinner.votes / updatedDenominator;
-        currentWinner.denominator = updatedDenominator;
-        currentWinner.quotient = updatedQuotient;
+        const winner = _.sample(currentWinners);
```
Comment (simendag) [inline src/computation/logic/algorithm-utilities.ts:96]: Why is a random currentWinner being chosen here?

Comment (simendag) [reply src/computation/logic/algorithm-utilities.ts:96]: Oh, nevermind, just a poorly chosen name for `currentWinners` -- they are per definition cases of equal votes (and quotient).

Comment (Log234) [reply src/computation/logic/algorithm-utilities.ts:96]: Yes, the naming could be improved.
